name: Spring Boot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configurar Java (usa la versión de tu proyecto, por ejemplo 17 o 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # 3️⃣ Descargar dependencias y compilar
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      # 4️⃣ (Opcional) Ejecutar pruebas unitarias
      - name: Run tests
        run: mvn test

