name: Java CI

on:
  push:
    branches: [ 'develop', 'main' ]
  pull_request:
    branches: [ 'develop', 'main' ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Run unit tests with coverage
        working-directory: ./demo
        run: mvn -B -ntp clean test

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: demo/target/site/jacoco/jacoco.csv
          badges-directory: .github/badges
          generate-branches-badge: true
          generate-summary: true

      - name: Log coverage percentage
        run: |
          echo "Coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "Branches = ${{ steps.jacoco.outputs.branches }}"

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: demo/target/site/jacoco/

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: demo/target/surefire-reports
