name: Java CI

on:
  push:
    branches: [ 'develop', 'main' ]
  pull_request:
    branches: [ 'develop', 'main' ]

jobs:
  build:
    name: Build, test and package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build and run tests (Maven)
        working-directory: ./demo
        run: mvn -B -ntp verify



